name: Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8.0_333
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Install dependencies
      run: mvn install -DskipTests
      continue-on-error: true

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Set up virtual display
      run: |
            export DISPLAY=:99
            sudo Xvfb :99 -screen 0 1280x1024x24 +extension RANDR &

    - name: Run Cucumber tests
      run: mvn test
